/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package quanlysf.ui;

import javax.swing.JOptionPane;

import quanlysf.DAO.Costumer;
import quanlysf.DAO.CostumerDAO;
import quanlysf.DAO.Employee;
import quanlysf.DAO.EmployeeDAO;

/**
 *
 * @author dinhd
 */
public class CustomerAdd extends javax.swing.JDialog {
    CostumerDAO costumerDAO;
    Costumer previouseCustomer = null;
    private EmployeesSearch employeesSearch;
    private boolean updateMode = false;
    /**
     * Creates new form CustomerAdd
     */
    public CustomerAdd(java.awt.Frame parent, boolean modal,EmployeesSearch thewEmployeesSearch, CostumerDAO thCostumerDAO, Costumer thPreviousCostumer, boolean theUpdateMode) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        costumerDAO = thCostumerDAO;
        employeesSearch = thewEmployeesSearch;
        previouseCustomer = thPreviousCostumer;
        updateMode = theUpdateMode;

        if (updateMode) {
            setTitle("Update Customer");
            populateFormFields(previouseCustomer);
        } else {
            setTitle("Add Customer");
        }
    }

    private void populateFormFields(Costumer previouseCustomer) {
        CNameTextField.setText(previouseCustomer.getCname());
        CAddressTextField.setText(previouseCustomer.getCaddress());
        int CustomerPhone = previouseCustomer.getCnumber();
        CPhoneTextField.setText(String.valueOf(CustomerPhone));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CNameTextField = new javax.swing.JTextField();
        CAddressTextField = new javax.swing.JTextField();
        CPhoneTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        CNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CNameTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("Customer Name");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel4.setText("Customer Address");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel5.setText("Customer Phone Number");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                        .addComponent(btnCancel))
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CNameTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CAddressTextField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CPhoneTextField, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CPhoneTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnAdd))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CNameTextFieldActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        saveCustomer();
    }//GEN-LAST:event_btnAddActionPerformed

    private void saveCustomer() {
        String CustomerName = CNameTextField.getText();
        String CustomerAddress = CAddressTextField.getText();
        String CostumerPhoneTxt = CPhoneTextField.getText();
        int CPhone = Integer.parseInt(CostumerPhoneTxt);

        Costumer temCostumer = null;

        if (updateMode) {
            temCostumer = previouseCustomer;

            temCostumer.setCname(CustomerName);
            temCostumer.setCaddess(CustomerAddress);
            temCostumer.setCnumber(CPhone);
        } else {
    // lẽ ra là CID nhưng pass dữ liệu nào cũng được vì trong CostumerDaoimp không có set CID
            temCostumer = new Costumer(CPhone, CustomerName, CustomerAddress, CPhone);
        }

        try {
            if (updateMode) {
                costumerDAO.update(temCostumer);
            } else {
                costumerDAO.insert(temCostumer);
            }

            setVisible(false);
            dispose();
            
            //refresh gui list
            employeesSearch.refreshCostumerView();
        JOptionPane.showMessageDialog(employeesSearch,"Custumer add succesfully.","Custumer Added",JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception exc) {
            JOptionPane.showMessageDialog(
                employeesSearch, "Error saving customer: " + exc.getMessage(),
                "Error", JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CustomerAdd dialog = new CustomerAdd(new javax.swing.JFrame(), true, employeesSearch, costumerDAO, previouseCustomer, updateMode);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CAddressTextField;
    private javax.swing.JTextField CNameTextField;
    private javax.swing.JTextField CPhoneTextField;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
